apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}        # 2 in default, 1 in dev, 3 in prod
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: {{ .Values.app.resources.requests.memory | quote }}
              cpu: {{ .Values.app.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.app.resources.limits.memory | quote }}
              cpu: {{ .Values.app.resources.limits.cpu | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
spec:
  selector:
    app: fastapi-app
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  type: {{ .Values.app.service.type }}
