apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
type: Opaque
data:
  # b64enc encodes the value from values.yaml to base64 automatically
  # No need to manually run echo -n "value" | base64 anymore
  POSTGRES_USER:     {{ .Values.secrets.POSTGRES_USER     | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc }}
  REDIS_PASSWORD:    {{ .Values.secrets.REDIS_PASSWORD    | b64enc }}
